org.gradle.jvmargs=-Xmx2G

minecraft_version=26.1.2
enabled_platforms=fabric,neoforge

archives_base_name=RuOK
mod_version=1.7.0
maven_group=team.teampotato.RuOK

fabric_loader_version=0.19.3
fabric_api_version=0.155.2+26.1.2
neoforge_version=26.1.2.93

# Loom / Architectury / Shadow
loom_version=1.17.491
architectury_plugin_version=3.5.169
shadow_version=9.4.2

# Cloth Config
cloth_config_version=26.1.154





